version: '3.8'

services:
  db-mongo:
    image: mongo:6.0
    container_name: pantry_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - pantry-network

  db-postgres:
    image: postgres:15
    container_name: pantry_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pantry_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pantry-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: pantry_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - pantry-network

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: pantry_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - pantry-network

  frontend-service:
    build: ./frontend-service
    container_name: service_frontend
    ports:
      - "5000:5000"
    networks:
      - pantry-network
    depends_on:
      recipe-service:
        condition: service_started
      pantry-service:
        condition: service_started
      planning-service:
        condition: service_started

  recipe-service:
    build: ./recipe-service
    container_name: service_recipe
    ports:
      - "5001:5000"
    depends_on:
      - db-mongo
    restart: on-failure:5
    environment:
      MONGO_URI: "mongodb://db-mongo:27017"
    networks:
      - pantry-network
  
  pantry-service:
    build: ./pantry-service
    container_name: service_pantry
    ports:
      - "5002:5000"
    depends_on:
      - db-postgres
    restart: on-failure:5
    environment:
      DATABASE_URL: "postgresql://user:password@db-postgres/pantry_db"
    networks:
      - pantry-network

  planning-service:
    build: ./planning-service
    container_name: service_planning
    ports:
      - "5003:5000"
    depends_on:
      - db-postgres
      - recipe-service
    restart: on-failure:5
    environment:
      DATABASE_URL: "postgresql://user:password@db-postgres/pantry_db"
    networks:
      - pantry-network

volumes:
  mongo_data:
  postgres_data:

networks:
  pantry-network:
    driver: bridge